language:
    - cpp

env:
 global:
    - "ARTIFACTS_AWS_REGION=eu-west-1"
    - "ARTIFACTS_S3_BUCKET=artm"
    - secure: "fgg2171sJW3OgG41rw4y/Guf31KPl2xQ8N1TukZ2oSfwSx6GsP5PPBISCt9kwUFAHuL5Sd9Qxx+2Quu7zHMPyM+wEXagtqN4LmS9pwXbze2GTqD6E6PA7dB8LA+EDq0d/3g34GunkXtF+Y1rjmuay9AKV07L6Mi4OJ7qa8brpHE="
    - secure: "TaDH0cDG9/oO/nOZ0jv+sE0soc3uQ+sAULyj9om9W9esvuYU3fjiN7IyJCmzjvpaGtub5cHKObKwtclxFjzsd71KnYqbZ/JWngL1rD7Cjrc3IoUmd/K9UQdH8T2/zfhx8ZJP2sjP8t0+kIzttXuYW2gXRdlsOBXHVtvkWlgKjc4="

compiler:
    - clang

before_install:
    - "gem install travis-artifacts"

script:
    - mkdir _builds

after_script:
    - "travis-artifacts upload --path test.cpp"